[project]
name = "tankly-api"
version = "0.1.0"
entry_point = "main.py"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.0",
]
